services:
  postgres:
    image: postgres:17
    container_name: pg-multitenant
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
